name: dev-integration-test
on:
  push:
    branches:
      - dev   
jobs:
  integration-test-privacy:
    runs-on: ubuntu-latest
    timeout-minutes: 10    
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.INTEGRATION_SLACK_WEBHOOK }}
    steps:
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.1'
      - name: Checkout ident
        uses: actions/checkout@v2
        with:
          repository: provideapp/ident
          path: 'ident'
          ref: dev
          token: ${{ secrets.DEPLOY_GITHUB_PAT }}             
      - name: Checkout privacy
        uses: actions/checkout@v2
        with:
          path: 'privacy'                      
      - run: docker-compose -f ./ops/docker-compose.yml build --no-cache privacy
        working-directory: privacy
      - run: docker-compose -f ./ops/docker-compose.yml up -d
        working-directory: privacy
      - run: TAGS=integration ./ops/run_local_tests.sh
        working-directory: privacy
      - run: docker-compose -f ./ops/docker-compose.yml logs
        working-directory: privacy
      - run: docker-compose -f ./ops/docker-compose.yml down
        working-directory: privacy
      - run: docker volume rm ops_privacy-db
        working-directory: privacy                                        
      - name: slack channel update
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: always()  
