name: Privacy (dev)
on:
  push:
    branches:
      - dev

jobs:
  push-to-registry:
    name: Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        id: checkout
        uses: actions/checkout@v2
      - name: Push Docker Image 
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PAT }}
          repository: provide/privacy
          tags: dev
