name: Hourly Integration
on:
  schedule:
    - cron: '0,30 * * * *'  # every half hour  
jobs:
  integration-test-privacy:
    runs-on: ubuntu-latest
    timeout-minutes: 10    
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.INTEGRATION_SLACK_WEBHOOK }}
    steps:
      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Checkout ident
        uses: actions/checkout@v2
        with:
          repository: provideplatform/ident
          path: 'ident'
          ref: dev
      - name: Checkout privacy
        uses: actions/checkout@v2
        with:
          path: 'privacy'
      - run: docker build -t privacy-under-test .
        working-directory: privacy
      - run: docker-compose -f ./ops/docker-compose.yml up -d
        working-directory: privacy
      - run: TAGS=integration ./ops/run_integration_tests.sh
        working-directory: privacy
      - run: docker-compose -f ./ops/docker-compose.yml logs
        working-directory: privacy
      - run: docker-compose -f ./ops/docker-compose.yml down
        working-directory: privacy
      - run: docker volume rm ops_privacy-db
        working-directory: privacy
      - name: Send Slack Notification
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: failure()
