name: Unit Tests
on:
  push:
    branches:
      - dev
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout privacy
        uses: actions/checkout@v2
        with:
          path: 'privacy'
      - run: echo "LOG_LEVEL=info" >> $GITHUB_ENV
      - run: echo "DATABASE_HOST=localhost" >> $GITHUB_ENV
      - run: echo "DATABASE_NAME=privacy_dev" >> $GITHUB_ENV
      - run: echo "DATABASE_PORT=5432" >> $GITHUB_ENV
      - run: echo "DATABASE_USER=privacy" >> $GITHUB_ENV
      - run: echo "DATABASE_PASSWORD=privacy" >> $GITHUB_ENV
      - run: echo "DATABASE_SUPERUSER=prvd" >> $GITHUB_ENV
      - run: echo "DATABASE_SUPERUSER_PASSWORD=prvdp455" >> $GITHUB_ENV
      - run: echo "DATABASE_SSL_MODE=disable" >> $GITHUB_ENV
      - run: echo "DATABASE_LOGGING=false" >> $GITHUB_ENV
      - run: echo "SEAL_UNSEAL_VALIDATION_HASH=0x7cff64a2d2b709dd9df196000be6237875bafe0a92873fd9fd9f35c00808f309" >> $GITHUB_ENV
      - run: echo "TAGS=unit" >> $GITHUB_ENV
      - run: echo "JWT_SIGNER_PUBLIC_KEY=${{ secrets.DEV_JWT }}" >> $GITHUB_ENV                 
      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.1'
      - name: Checkout ident
        uses: actions/checkout@v2
        with:
          repository: provideapp/ident
          path: 'ident'
          ref: master
          token: ${{ secrets.DEPLOY_GITHUB_PAT }}
      - run: make build
        working-directory: privacy
      - run: make test
        working-directory: privacy
      - run: docker volume rm ops_privacy-db
